### ISSUE TITLE
Infografía Ingeniería de requisitos Concepción

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/infografia-MariaC232#2]
[Ingenieria de requisitos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-MariaC232/files/6094188/Ingenieria.de.requisitos.pdf)

**Comment by Jaci14** [comment]
1.- Falto incluir la información de las fases de la ingeniería de requisitos y su aplicación 
2.- faltaron mas imágenes. 
calificación: 17%

**Comment by josealfredo79** [comment]
Falta las fases de la Ingeniería de Requerimientos...

**Comment by Jaci14** [comment]
Se corrigieron los temas que faltaban, aunque quizas tenga que utilizar colores mas llamativos 
Calificacion: 19%
